### ISSUE TITLE
Question on this particular construct.

### ISSUE THREAD

**Issue by ienapliss** [samuel-lucas6/ChaCha20-BLAKE2b#3]
Why not deriving just the key for calculating the tag and reusing the master key for encrypting the message?
Is there a security reason?

**Comment by samuel-lucas6** [comment]
It's to make the construction [committing](https://eprint.iacr.org/2017/664.pdf). This prevents the ciphertext from being successfully decrypted under multiple different keys, which is a limitation of constructions like AES-GCM and (X)ChaCha20-Poly1305.

You either use a single key for both encryption and authentication, which is not recommended for Encrypt-then-MAC, or you use a KDF to derive both the encryption key and MAC key from the same input keying material.

A more efficient approach would be to derive both keys in one call, like Frank does in his [XChaCha20-SIV](https://github.com/jedisct1/libsodium-xchacha20-siv) construction using BLAKE2b-512, but then you get a unique encryption key each time, which is rather wasteful with a nonce.

Hope that helps!

**Comment by ienapliss** [comment]
Thank you for the detailed response, much appreciated!
